### ISSUE TITLE
Open side ViewController without pressing the button

### ISSUE THREAD

**Issue by ftp27** [MUSTLaboratory/MLFlyOverMenu#3]
Thank you for the easy to use library. But I need to ask you to give us a training video it would save plenty of time. We need to open side ViewController without pressing the button and it may be very useful if we have any delegate class for getting events with open and close side ViewController.

**Comment by xtazz** [comment]
Hi! You may just use swipe gesture recognizer and perform menu open segue when it fires. Please let me know if you need more details

**Comment by ftp27** [comment]
I use presenting ViewController for displaying chat messages. Therefore I need to open the ViewController without storyboard. Also I need to open the ViewController with special width equals ~ screenWidth-100, I can't do this from storyboard with User Defined Runtime Attributes

**Comment by ftp27** [comment]
I managed to do it!

It works like this:

``` Objective-C
- (IBAction)openMenu:(id)sender {
    if (!self.flyOverMenuController.presentingViewController) {
        [self performSegueWithIdentifier:@"ml_from_right" sender:sender];
        ChatViewController *chat = (ChatViewController *) self.flyOverMenuController.contentViewController;
        chat.socket = self.socket;
        self.chatDelegate = chat;
    }
}

- (IBAction)closeMenu:(id)sender {
    if (self.flyOverMenuController.presentingViewController) {
        [self performSegueWithIdentifier:@"ml_from_right" sender:sender];
        self.chatDelegate = nil;
    }
}
```

**Comment by xtazz** [comment]
@ftp27 you can close the menu by calling dismissAnimated method without checking for presentingViewController

**Comment by xtazz** [comment]
@ftp27 also you can configure the width of menu by implementing method contentWidthInFlyOverMenu in your menu's view controller

**Comment by xtazz** [comment]
@ftp27 и желаю удачи)

**Comment by ftp27** [comment]
@xtazz Спасибо! Попробую поиграть с шириной, но, правда, и так пока выглядит вполне сносно :)
